spring:
  application:
    name: cloud-api-gateway

  config:
    import: "optional:configserver:"

  cloud:
    gateway:
      routes:
        - id: user-client
          uri: http://localhost:2011
          predicates:
            - Path=/divyansh/**

        - id: library-mvc-project
          uri: http://localhost:2010
          predicates:
            - Path=/library/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9091/eureka

server:
  port: 9090
